from typing import Any

from migrateit.clients._client import SqlClient
from migrateit.cmd import cmd_export


def _ensure_root_applied(client: SqlClient[Any]) -> None:
    """Apply the root migration if it hasn't been already.

    Session-scoped PostgreSQL connections may carry state between tests,
    so the root migration might already be applied.
    """
    client.apply_migration(client.changelog.root, is_fake=True)
    client.connection.commit()


def test_cmd_export_no_name_creates_default(client: SqlClient[Any]) -> None:
    """Test cmd_export creates a migration with a default name when no name is provided."""
    _ensure_root_applied(client)
    result = cmd_export(client, name=None)

    assert result == 0
    # Default name should be <database>_backup, prefixed with 0001_
    expected_name = f"{client.changelog.database.value}_backup"
    changelog_names = [m.name for m in client.changelog.migrations]
    assert any(expected_name in name for name in changelog_names)


def test_cmd_export_with_name(client: SqlClient[Any]) -> None:
    """Test cmd_export creates a migration with the provided name."""
    _ensure_root_applied(client)
    result = cmd_export(client, name="my_full_export")

    assert result == 0

    # Verify migration depends on root
    export_migration = next(m for m in client.changelog.migrations if "my_full_export" in m.name)
    assert export_migration.parents == [client.changelog.root.name]

    # Verify migration file exists
    changelog_names = [m.name for m in client.changelog.migrations]
    files = list(client.migrations_dir.glob("*my_full_export*.sql"))
    assert any("my_full_export" in name for name in changelog_names)
    assert len(files) == 1

    # Verify migration content
    content = files[0].read_text()
    assert "-- Rollback migration" in content
    assert "Migration automatically generated by migrateit" in content
