name: Code Quality and Testing
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.13"
            postgres-version: "17"
            mysql-version: "9.7"
          - python-version: "3.14"
            postgres-version: "18"
            mysql-version: "26.7"

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: migrateit
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_DATABASE: migrateit
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install MigrateIt
        run: |
          pip install -e .

      - name: Copy environment variables (CI requires .env file)
        run: |
          cat .testenv > .env

      - name: Pytest + code coverage
        run: |
          export $(cat .env | xargs) &&
          coverage run -m pytest &&
          coverage report -m

      - name: Test coverage
        run: |
          export $(cat .env | xargs) &&
          coverage run --source=tests -m pytest &&
          coverage report -m --fail-under=100
