name: Code Quality and Testing
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        postgres-version: ["15", "17"]

    services:
        postgres:
            image: postgres:${{ matrix.postgres-version }}
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: postgres
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Copy environment variables (CI requires .env file)
        run: |
            cat .testenv > .env

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install migrateit
        run: |
          pip install -e .

      - name: Pytest + code coverage
        run: |
            export $(cat .env | xargs) &&
            coverage run -m pytest &&
            coverage report -m

      - name: Test coverage
        run: |
            export $(cat .env | xargs) &&
            coverage run --source=tests -m pytest &&
            coverage report -m --fail-under=100
